# Generated by Django 4.1.6 on 2023-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
