# Generated by Django 4.1.6 on 2023-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
