# Generated by Django 4.1.6 on 2023-02-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='season',
        ),
    ]
