# Generated by Django 4.1.6 on 2023-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_article_season'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
