# Generated by Django 4.1.6 on 2023-02-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_article_season_delete_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('season_id', models.CharField(max_length=222)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.season'),
            preserve_default=False,
        ),
    ]
